baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

enableRobotsTXT: true

#services:
#googleAnalytics:
#id: G-MEASUREMENT_ID
#disqus:
#shortname: your-disqus-shortname

pagination:
  pagerSize: 3

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
#  main:
#- identifier: blog
#  name: Blog
#  title: Blog posts
#  url: /blogs
#  weight: 1
#- identifier: gallery
#  name: Gallery
#  title: Blog posts
#  url: /gallery
#  weight: 2
#Dropdown menu
# - identifier: dropdown
#   title: Example dropdown menu
#   name: Dropdown
#   weight: 3
# - identifier: dropdown1
#   title: example dropdown 1
#   name: example 1
#   url: /#
#   parent: dropdown
#   weight: 1
# - identifier: dropdown2
#   title: example dropdown 2
#   name: example 2
#   url: /#
#   parent: dropdown
#   weight: 2

params:
  title: "Manel YALA's Portfolio"
  description: This is my portfolio
  # staticPath: ""  # The path to serve the static files from
  favicon: ""

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Manel's Portfolio" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hello there, I'm"
    title: "Manel"
    subtitle: "I turn your data into decisions"
    content: "I'm a young and passionate data scientist with a strong background in AI. I build smart solutions that transform raw data into impactful insights"
    #image: /fav.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/yalamanel/
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/manel-yala/

  # About
  about:
    enable: true
    title: "About Me"
    image: #"/img/me.jpeg"
    content: |-
      Recently graduated from a top-ranked program in France, I've always been fascinated by how artificial intelligence can serve people and enhance human potential.

      My key strength? I thrive at the intersection of technical teams and business stakeholders.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Pytorch"
        - "MLFlow"
        - "Databricks"
        - "LangChain"
        - "Hugging Face Transformers"
        - "Docker"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - company: "Les Mousquetaires Group"
        companyUrl: "https://www.mousquetaires.com/"
        jobs:
          - name: "Data Scientist"
            date: "Apr 2025 - Sep 2025"
            content: "I completed my final-year internship as a Data Scientist at STIME, the IT department of the Les Mousquetaires Group. I contributed to a deep learning project aimed at forecasting cash flows to support business teams in their financial decision-making."
            #info:
            #cd   content: Working as a senior software developer
            featuredItems:
              customIcons:
                - icon: /img/python.png
                  url: #"https://example.com"
                  tooltip: Python

                - icon: /img/azure.png
                  url: #"https://example.com"
                  tooltip: Microsoft Azure

                - icon: /img/pytorch.png
                  url: #"https://example.com"
                  tooltip: Pytorch

                - icon: /img/databricks.png
                  url: #"https://example.com"
                  tooltip: Databricks

                - icon: /img/mlflow.svg
                  url: #"https://example.com"
                  tooltip: MLFlow

      - company: "LATMOS"
        companyUrl: "https://latmos.ipsl.fr/fr/"
        jobs:
          - name: "AI Research Assistant"
            date: |
              Apr 2024 - Sep 2024  
              Feb 2025 - Mar 2025
            info:
              content: "After a successful 6-month internship, I was invited back for an additional 2-month research internship to further enhance the project and implement key improvements."
            content: |
              During a research internship at LATMOS, under the academic supervision of Sorbonne Université, I worked on precipitation nowcasting using satellite-derived cloud temperature data. I explored and implemented deep learning convolutional architectures applied to geospatial imagery with the goal of improving short-term weather forecasting accuracy.
            featuredItems:
              customIcons:
                - icon: /img/python.png
                  url: #"https://example.com"
                  tooltip: Python

                - icon: /img/pytorch.png
                  url: #"https://example.com"
                  tooltip: Pytorch

                - icon: /img/linux.png
                  url: #"https://example.com"
                  tooltip: Linux

                - icon: /img/github.png
                  url: #"https://example.com"
                  tooltip: Github

      - company: "BPCE Group"
        companyUrl: "http://www.natixis.dz"
        jobs:
          - name: "Data Analyst"
            date: "Jan 2020 - Aug 2020"
            featuredItems:
              customIcons:
                - icon: /img/python.png
                  url: #"https://example.com"
                  tooltip: Python

                - icon: /img/oracle.png
                  url: #"https://example.com"
                  tooltip: Oracle BI

                - icon: /img/sklearn.png
                  url: #"https://example.com"
                  tooltip: Sci-Kit Learn

                - icon: /img/brevo.png
                  url: #"https://example.com"
                  tooltip: Brevo

            content: |
              During my internship at BPCE Group (Natixis), I worked on the analysis and valorization of banking data. I designed interactive dashboards and led a clustering project to gain deeper insights into customer behavior.

      - company: "OTA Djezzy"
        companyUrl: "https://www.djezzy.dz"
        jobs:
          - name: "Data Scientist"
            date: "Jan 2022 - Jun 2022"
            featuredItems:
              customIcons:
                - icon: /img/python.png
                  url: #"https://example.com"
                  tooltip: Python

                - icon: /img/pytorch.png
                  url: #"https://example.com"
                  tooltip: Pytorch

                - icon: /img/tensorflow.png
                  url: #"https://example.com"
                  tooltip: tensorflow

                - icon: /img/sql.png
                  url: #"https://example.com"
                  tooltip: SQL

                - icon: /img/django.svg
                  url: #"https://example.com"
                  tooltip: Django
            content: |
              During my internship at Djezzy, I worked on telecom fraud detection using machine learning. I developed predictive models based on big data sources—including call records, SMS, and mobile data—emphasizing advanced feature engineering and production deployment.

      - company: "Pitch Events"
        companyUrl: #"https://example.com"
        jobs:
          - name: "BI Analyst and MERN Stack Developer"
            date: "Nov 2022 - May 2023"
            featuredItems:
              customIcons:
                - icon: /img/powerbi.png
                  url: #"https://example.com"
                  tooltip: PowerBI

                - icon: /img/react.png
                  url: #"https://example.com"
                  tooltip: React

                - icon: /img/mongodb.webp
                  url: #"https://example.com"
                  tooltip: MongoDB

            content: |
              I contributed to the design and development of a cross-platform solution for access management and participant tracking at client events. I also built and presented analytical reports based on data collected through the app, providing actionable recommendations to optimize the organization of future events.

  #
  #
  #
  #
  #
  #
  #

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Science - Data Science and Information Processing (TRIED)"
        school:
          name: "Paris-Saclay University – Institut Polytechnique de Paris"
          #url: "https://example.org"
        date: "2024 - 2025"
        GPA: "3.3 out of 5.0"
        content: |-
          Ranked among the Top 10 Data Science programs in France, focused on statistical analysis, machine learning, and deep learning.

          Key modules: Machine Learning & Deep Learning, Advanced Statistics, Data Analysis, Databases \& Big Data.
      #
      #
      #

      - title: "Master of Science - Artificial Intelligence"
        school:
          name: "University of Science and Technology Houari Boumediene"
          # url: "https://example.org"
        date: "2022 - 2024"
        #GPA: "3.9 out of 5.0"
        content: |-
          Extracurricular Activities
            - Student Representative (2020–2022) : Elected representative of my class, acting as liaison between students and academic administration to improve the learning environment.

            - Member – IT Section, Micro Club USTHB (2019–2024) : Active participant in Algeria’s oldest student tech club, contributing to workshops, hackathons, and tech awareness initiatives.

            - Head of Events & Logistics – Micro Club (2021–2023) : Organized and coordinated national-scale tech events and co-organizing flagship, regional, and international conferences.
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"

      - title: "Bachelor - Computer Science"
        school:
          name: "University of Science and Technology Houari Boumediene"
          #url: "https://example.org"
        #GPA: "4.2 out of 5.0"
        date: "2019 - 2022"
        featuredLink:
          enable: false
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    title: "Activities and Achievements"
    items:
      - title: Best Young Company Award
        content: Won the Best Young Company Award for developing Wink, an innovative high-impact solutions on a national level.
        image: /img/injaz.jpeg

      - title: MENA Regional Representative
        content: Represented Algeria at the Injaz Al-Arab entrepreneurship competition, presenting our startup solution before major partners including Google and Boeing.
        image: /img/injaz_arab.jpeg

      - title: Head of Events & Logistics Department
        content: Led and managed a 40+ member department, overseeing recruitment, training, and national-level event organization.
        image: /img/ops.png

      - title: Innovation Award
        content: Received the Innovation Award for delivering the most creative and impactful solution during the PMIEF Ideathon.

      - title: Dale Carnegie Leadership and Communication
        content: Completed a 3-day Dale Carnegie bootcamp focused on leadership, teamwork, communication, and problem-solving skills.

  # projects
  projects:
    enable: true
    title: "Other Projects"
    items:
      - title: Modeling Social Dynamics through Network Science and Graph Learning
        content: Explored social dynamics in university networks using graph learning and network science techniques. Analyzed large-scale friendship data to uncover community structures, predict new connections, and model how social ties evolve over time.
        image: /img/GL.jpg
        featured:
        badges:
          - "Graph Learning"
          - "Community Detection"
          - "Python"
          - "NetworkX"
      #        links:
      #          - icon: fa fa-envelope
      #            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
      #          - icon: fab fa-github
      #            url: https://github.com/gurusabarish/hugo-profile
      #          - icon: fab fa-twitter
      #            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile
      - title: EEG-Based Alzheimer Classification
        content: In collaboration with Samovar Lab, I developed machine learning and deep learning models to classify EEG brain signals from individuals with Alzheimer’s disease, mild cognitive impairment, and healthy controls. Explored different brainwave patterns to detect early neural signatures of cognitive decline.
        image: /img/EEG.png
        #featured:
        #  name: Demo
        #  link: https://django-converter.herokuapp.com
        badges:
          - "Biomedical Data Science"
          - "Signal Processing"
          - "Deep Learning"
          - "Python"

        #links:
        #  - icon: fab fa-github
        #    url: https://github.com/gurusabarish/converter

      - title: Interactive Power BI Dashboard for Event Participant Analytics
        content: Built an interactive Power BI dashboard to analyze participant data from an international event. The dashboard tracks attendance across rooms, sectors, and specialties, visualizing key insights on participant distribution, professional roles, and engagement.
        image: /img/BI.png
        #featured:
        #  name: Demo V2
        #  link: https://hugo-profile-2.netlify.app
        badges:
          - "Power BI"
          - "Dashboard Design"
          - "Data Storytelling"
          - "Reporting"
          - "KPI Tracking"
        #links:
        #  - icon: fab fa-github
        #    url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question, want to collaborate or just want to say hi, I’ll get back to you asap!
    btnName: Mail me
    btnLink: mailto:yalamanel@hotmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/yalamanel/
      linkedin: https://www.linkedin.com/in/manel-yala/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
